import { NextResponse } from "next/server";
import fs from "node:fs/promises";
import path from "node:path";
import {
  characterMotionGlbDir,
  characterMotionIndexPath,
  characterMotionLibraryDir,
  characterRootDir,
  getDesktopUserDataDir,
  isDesktopRuntimeEnabled,
} from "@/lib/desktop/desktopPaths";
import {
  loadCharacterSettings,
  sanitizeCharacterId,
  saveCharacterSettings,
} from "@/lib/desktop/desktopSettingsStore";

export const runtime = "nodejs";

type MotionIndex = {
  version: number;
  notes?: string;
  motions: Array<{ name: string; kind: "idle" | "talk" | "gesture"; path: string; source?: string }>;
};

function jsonError(message: string, status = 400) {
  return NextResponse.json({ ok: false, error: message }, { status });
}

function guessKind(filename: string): "idle" | "talk" | "gesture" {
  const s = filename.toLowerCase();
  if (s.includes("idle")) return "idle";
  if (s.includes("talk") || s.includes("speech")) return "talk";
  return "gesture";
}

function safeBasename(filename: string) {
  const base = path.basename(filename).replace(/[^a-zA-Z0-9._-]/g, "_");
  return base || "motion.glb";
}

export async function POST(req: Request) {
  if (!isDesktopRuntimeEnabled()) return jsonError("Desktop runtime is not enabled.", 404);
  const u = new URL(req.url);
  const char = sanitizeCharacterId(u.searchParams.get("char") ?? "");
  if (!char) return jsonError("Invalid char.", 400);

  const userData = getDesktopUserDataDir();
  if (!userData) return jsonError("Desktop runtime is not enabled.", 404);

  const form = await req.formData().catch(() => null);
  if (!form) return jsonError("Missing form data.", 400);

  const root = characterRootDir(userData, char);
  const libDir = characterMotionLibraryDir(userData, char);
  const glbDir = characterMotionGlbDir(userData, char);
  await fs.mkdir(root, { recursive: true });
  await fs.mkdir(glbDir, { recursive: true });

  const uploaded: string[] = [];
  const importedIndex = form.get("motionsJson");
  let index: MotionIndex | null = null;

  if (importedIndex instanceof File) {
    const raw = Buffer.from(await importedIndex.arrayBuffer()).toString("utf8");
    try {
      const j = JSON.parse(raw) as MotionIndex;
      if (j && typeof j.version === "number" && Array.isArray(j.motions)) index = j;
    } catch {
      // ignore
    }
  }

  // Upload any .glb files provided (field name: glbs)
  const glbs = form.getAll("glbs").filter((x): x is File => x instanceof File);
  for (const f of glbs) {
    const name = safeBasename(f.name || "motion.glb");
    const out = path.join(glbDir, name);
    await fs.writeFile(out, Buffer.from(await f.arrayBuffer()));
    uploaded.push(name);
  }

  // If no motions.json was provided, synthesize a minimal one from uploaded glbs.
  if (!index) {
    const motions = uploaded.map((file) => {
      const base = file.replace(/\.glb$/i, "");
      return {
        name: base,
        kind: guessKind(file),
        path: `converted/glb/${file}`,
        source: "desktop",
      };
    });
    index = { version: 1, notes: "generated by desktop import", motions };
  }

  // Write motions.json to the character motion-library.
  await fs.mkdir(libDir, { recursive: true });
  const indexPath = characterMotionIndexPath(userData, char);
  await fs.writeFile(indexPath, JSON.stringify(index, null, 2) + "\n", "utf8");

  const prev = (await loadCharacterSettings(char)) ?? null;
  if (prev) {
    const next = {
      ...prev,
      motions: { ...prev.motions, enabled: true, indexPath: "motion-library/motions.json" },
    };
    await saveCharacterSettings(next);
  }

  return NextResponse.json({
    ok: true,
    uploaded,
    motionsCount: index.motions.length,
    indexPath,
  });
}

